### ISSUE TITLE
TODO: Complete Maintainers file

### ISSUE THREAD

**Issue by kelset** [react-native-community/.github#1]
Let's complete the table with the full list of repositories in the org and the maintainers and status.

**Comment by kelset** [comment]
Hey everyone

@thymikee, @grabbou, @Esemesek, @sibelius, @emilioicai, @jamonholmgren, @Titozzz, @Krizzu, @dmtrKovalenko, @radex, @zoontek, @rborn, @christopherdro, @salah-ghanim, @cobarx, @michalchudziak, @Trancever, @msand, @satya164, @jgcmarins, @ferrannp, @bartolkaruza, @gre, @kmagiera, @kmagiera, @DanielZlotin, @Ansalibrahim, @Swaagie, @dabit3, @melihberberolu, @matt-oakes, @pvinis, @ivanzotov, @vonovak, @FonDorn, @Kureev, @hannigand, @mmazzarolo, @rewieer, @janicduplessis, @charpeni, @brentvatne, @cesargdm, @jimmylee, @FruitieX, @alihamza, @harisbaig100, @rafaellincoln

By looking at the commit history of each repository in the org, it looks like you are maintainers for at least one of them - so I've added you to https://github.com/react-native-community/meta/blob/master/MAINTAINERS.md (if someone is missing please submit a PR 🤗)

In the scenario in which you are not super aware of what's happening, why I @-ed you here: basically, we are trying to give more structure to the whole RNCommunity as it is now the official community for react native.

You can see that there is a guidelines folder with some files, and through PRs we'll fill the stubs there so to give all of you a change to review and comment on those "suggestions".

I hope we will be able to get to a point where all the repos in this org are all aligned on some defaults so that we can increase the confidence of the larger developer community using React Native and the code contained (as also said in the README).

For reference, here is where the conversation started/happened:
* https://github.com/react-native-community/discussions-and-proposals/issues/63 (main one)
* https://github.com/react-native-community/discussions-and-proposals/issues/65
* https://github.com/react-native-community/discussions-and-proposals/issues/58
* https://github.com/react-native-community/discussions-and-proposals/issues/59
* https://github.com/react-native-community/discussions-and-proposals/issues/101
* https://github.com/react-native-community/discussions-and-proposals/issues/75

If you feel that noone of this lines up with how you want to maintain your library please comment it here, we can see how we can change things up for you or we can explore moving the repo out of the org - but hopefully we'll find a way to collaborate :)

Also, if you are not on the React Native Core Contributors Discord [please DM me over on twitter](https://twitter.com/Kelset) with the email you want to be invited with.

**Comment by kelset** [comment]
(also -> @nicholaslee119, @kdenz, @bestander, @mkonicek, @DanielMSchmidt, @gengjiawen, @empyrical, @jgfidelis, @brentvatne, @lelandrichardson)

**Comment by kelset** [comment]
Ok 9 days ago I pinged all of you but more than a few actually never replied.

I'll wait a week then I'll start considering kicking the repos out of the community org.

**Comment by vonovak** [comment]
> If you feel that none of this lines up with how you want to maintain your library please comment it here, we can see how we can change things up for you or we can explore moving the repo out of the org - but hopefully we'll find a way to collaborate :)

I think most people (myself included) never replied because they agree with what was outlined. 👍 I don't necessarily see a reason to move repos out of the org unless no one wants to maintain them 😢

**Comment by mmazzarolo** [comment]
Same here. 
I'm probably missing something @kelset, were you waiting for some active feedbacks/changes to the repos?  🤔

**Comment by kelset** [comment]
No no it was mostly a ping for the people who didn't reach out to me yet in any way 🤗 (as you can see there are like 40 people that I @-ed and like 20 still haven't reached out)


re: @vonovak 

> I don't necessarily see a reason to move repos out of the org unless no one wants to maintain them 😢

I'd really prefer to not touch repos for which I don't have a communication line with the maintainers, hence why moving them out instead of starting to ex. change the readme and archive the repo if it's been inactive for 6+ months.
And a repo being unmaintained is not necessarely a reason to move it out - absolutely - example: https://github.com/react-native-community/meta/pull/10

**Comment by dabit3** [comment]
Hey @kelset , what do we need to do?

**Comment by kelset** [comment]
1) feedback on the ongoing discussions in the other issues if you have time

2) 
> Also, if you are not on the React Native Core Contributors Discord please DM me over on twitter with the email you want to be invited with.

3) ensure that MAINTAINERS.md is correct -> https://github.com/react-native-community/meta/blob/master/MAINTAINERS.md (maybe the person @-ed is not really a maintainer/not anymore)

**Comment by sibelius** [comment]
we can remove `cameraview`, as react-native-camera does not use it anymore, it has a copy inside the repo

we moved examples back to react-native-camera, so `rncamera-example` can be removed

**Comment by rafaellincoln** [comment]
I think Discord is a better place to keep up with the work of the maintainers. Has group already been exists?

**Comment by rborn** [comment]
cc: @alvelig

**Comment by kelset** [comment]
@rafaellincoln, as I mentioned above, yes there is a Discord already - can you please DM me so that I can send you the invite link?

**Comment by kelset** [comment]
Quick update on this:

given that it's not easy to maintain a .md file with all the repos & the maintainers, following some conversation happened here: https://github.com/react-native-community/.github/pull/23 and on the Discord, we will be actually moving towards instead using the [CodeOwners file](https://help.github.com/en/articles/about-code-owners) in each of the repo.

It's going to be long effort but it will be more scalable in the long term.

I'd like to invite each maintainer to add that file with all the maintainers to the repo their are maintaining, I'll try to help over the next few weeks so that then we can modify the script Matt created to scrape it.

**Comment by kelset** [comment]
Ok, I've updated the Maintainers - now it's complete AFAIK.
