### ISSUE TITLE
Standardise folder organisation and naming

### ISSUE THREAD

**Issue by xzilja** [react-native-community/.github#17]
Familiar file organisation can go long way in terms of viewing and updating codebase.
We have different main code names for folders i.e. `src` vs `lib`, native code being nested in various subfolders etc..

I really enjoy how well structured `react-native-firebase` project is https://github.com/invertase/react-native-firebase/tree/master/packages

If you look inside any of these packages you will find same structure all across the board. I feel its very welcoming to contribute to and clear.

**Comment by pvinis** [comment]
netinfo is a good one too.

**Comment by grabbou** [comment]
Check out our too: https://github.com/react-native-community/cli. I think we are similar to Firebase with their workspaces setup.

Question: 
- What if a project doesn't have workspaces? 
- What we should do if we transfer a project that has a different structure?

To me, the structure is the end product of the build system used. If a project uses a build phase to e.g. ship already transpiled code to npm, the `build` and `src` will be the end result of it. 

Standardising the build system might solve this problem and not be perceived as a enforcement, but as a time-saver for developers.

**Comment by kelset** [comment]
yeah I think that the folder structure may be a bit too complex to standardize atm

**Comment by kelset** [comment]
While I still believe it's a bit too much, but maybe this could be a good inspiration: https://github.com/golang-standards/project-layout

**Comment by kelset** [comment]
Closing in favour of #31
