### ISSUE TITLE
TODO: complete the guidelines

### ISSUE THREAD

**Issue by kelset** [react-native-community/.github#2]
Currently just added the stubs so that the actual fillings can be discussed through PRs.

Some example/sources:
* https://github.com/Moya/contributors
* https://github.com/golang-standards/project-layout
* https://github.com/facebook/graphql/blob/master/CONTRIBUTING.md
* https://github.com/ocaml-community/meta
* https://github.com/Microsoft/TypeScript/wiki/Contributing-to-TypeScript
* https://jaxenter.com/dos-donts-keeping-changelog-147373.html
* https://boats.gitlab.io/blog/post/rust-2019/

**Comment by mikehardy** [comment]
haha - no merge unpunished! hop to it @kelset ;-)

**Comment by kelset** [comment]
Ahahahah 😅

Too many things to doooooo T_T

**Comment by lucasbento** [comment]
Bad stale.

**Comment by kelset** [comment]
This is also a really good source of inspiration https://github.com/Moya/contributors
