### ISSUE TITLE
TODO: complete the decisions around common health files

### ISSUE THREAD

**Issue by kelset** [react-native-community/.github#3]
Since we are going enforce those through GitHub allowing for [organization-wide community health files](https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/), we need to finalise the decisions around them.

From the link
> You can add CONTRIBUTING, SUPPORT, CODE_OF_CONDUCT, ISSUE_TEMPLATE(S), or PULL_REQUEST_TEMPLATE(S) files to a public, organization-owned .github repository, and if a given community health file doesn’t exist for a repository, the organization-wide default will be used.

Need to settle on:
- [ ] CONTRIBUTING
- [ ] SUPPORT
- [ ] CODE_OF_CONDUCT
- [x] ISSUE_TEMPLATE(S)
- [x] PULL_REQUEST_TEMPLATE(S)

**Comment by kelset** [comment]
For the COC we'll probably enforce the FB one -> https://github.com/react-native-community/discussions-and-proposals#coc

**Comment by dmtrKovalenko** [comment]
Maybe all the maintainers needs to be added to the organization, and share that stuff in the private organization repo?

**Comment by kelset** [comment]
>in the private organization repo?

There is no private org repo AFAIK, what are you referring to?

**Comment by kelset** [comment]
ping @dmtrKovalenko

**Comment by dmtrKovalenko** [comment]
Yep, I am here @kelset - that message was just an idea. Or smth else?

**Comment by kelset** [comment]
Ok - then probably the Discord is the best place, as mentioned [here](https://github.com/react-native-community/meta/issues/1) can you send me a DM so that we can comm over there too?

**Comment by kelset** [comment]
Hey folks, I'm going to close this issue. I should have probably closed it off once I stopped being an owner of the org and while some conversation around this happened I feel that given the "0 executive power" of these conversations it's better to just close them off - so not to give the misleading signal that something is currently being done on my side (or by anyone tbh) around it.

If and when this topic will get picked up again it's much healthier for whoever will actually handle it to just open a new issue. I'm not against the new issue picking up this same conversation, even copy/pasting stuff from here - but I want to close the ones opened up by me off.
