### ISSUE TITLE
BOTs in the org

### ISSUE THREAD

**Issue by kelset** [react-native-community/.github#30]
Basically, it seems that via this repo we can also share some probots configurations - since that the bots are installed at org level.

We are trying this feature out via the stalebot and this PR: https://github.com/react-native-community/.github/pull/29

But potentially we could also do other things, here are a couple of examples we could get some inspiration from:

- https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml
- https://github.com/home-assistant/codeowners-mention

If you have any ideas on something that we could automate via bots, to make life easier for the maintainers in the repo, please post them here!

**Comment by MateusAndrade** [comment]
Implementing something similar to react-native to handle issues labels, etc would be a great addition. 

We can automate the process on issues without label, pra, etc.

**Comment by matt-oakes** [comment]
The other public Probot apps are listed here: https://probot.github.io/apps/

Nothing jumps out as something we "need", except for maybe the one which closes issues if the reporter does not provide more information when requested.

**Comment by mikehardy** [comment]
> Nothing jumps out as something we "need", except for maybe the one which closes issues if the reporter does not provide more information when requested.

I love that idea though it's sort of a subset of "stale"

Coordinating the request info bot with regexes for community template strings to make sure people put in required things would be great - that's a big category of issues that are hard to handle https://probot.github.io/apps/request-info/ - the welcome bot could serve as belt+suspenders there as well, mentioning how important the template is

I'd go for lock threads as well, I really do not enjoy the zombie reanimation that occurs 2 major releases after something that's normally an install issue anyway

**Comment by kelset** [comment]
Hey folks, I'm going to close this issue. I should have probably closed it off once I stopped being an owner of the org and while some conversation around this happened I feel that given the "0 executive power" of these conversations it's better to just close them off - so not to give the misleading signal that something is currently being done on my side (or by anyone tbh) around it.

If and when this topic will get picked up again it's much healthier for whoever will actually handle it to just open a new issue. I'm not against the new issue picking up this same conversation, even copy/pasting stuff from here - but I want to close the ones opened up by me off.
