### ISSUE TITLE
Migrating a repo into the React Native Community

### ISSUE THREAD

**Issue by kelset** [react-native-community/.github#34]
We should really define "once and for all" what the flow for this should be, so that we can write it somewhere & communicate to people who wants to go for this.

At the moment, over time it sort of became standard to open an issue in the D&P repo, similar to what happened in this situation:

https://github.com/react-native-community/discussions-and-proposals/issues/135

I wonder if this should happen instead on this repo, so that it's not "noising" the other discussions.

Note: I don't want here & now define "what it takes" to have a repo join the Comm, just "the happy path". This other topic is probably literally a case-by-case scenario.

**Comment by kelset** [comment]
Btw, short list of things that should happen when moving a repo into the RNComm:
- main maintainer set to admin for the repo
- main maintainer added to the org as member + the maintainers team
- repo should be adding the codeowners file + the protect master branch settings

**Comment by lucasbento** [comment]
Also make sure that the main maintainer is in the React Native Community discord server.

**Comment by kelset** [comment]
Hey folks, I'm going to close this issue. I should have probably closed it off once I stopped being an owner of the org and while some conversation around this happened I feel that given the "0 executive power" of these conversations it's better to just close them off - so not to give the misleading signal that something is currently being done on my side (or by anyone tbh) around it.

If and when this topic will get picked up again it's much healthier for whoever will actually handle it to just open a new issue. I'm not against the new issue picking up this same conversation, even copy/pasting stuff from here - but I want to close the ones opened up by me off.
