### ISSUE TITLE
Organisation updates - PLEASE READ ❤️

### ISSUE THREAD

**Issue by kelset** [react-native-community/.github#40]
👋 folks!

As you may have noticed, I've (finally!) managed to work on #1 and finish it - if something doesn't look right submit a PR and/or let me know!

Aside from that, I've also added all the maintainers to the github org and to a team called Maintainers. This should have happened gradually when you were added as maintainers for any of the orgs, and it was long overdue and I'm sorry it took me so long to push this forward.

*(btw in case now you are receiving notifications for all the repos in the org, I'd recommend to simply unwatch the ones you are not working on 🤗)*

All of this should help you all to keep track of things going on, and finally recognise you as part of the community 🤗

A few more comms, in case you missed:
- if you are not in the React Native Contributors discord, please let me know!
- there is an eslint config all repos should use, you can read more here #2
- we are working on a template that can be used to quickly create new repos https://github.com/react-native-community/template
- and many more things, please look at open issues!

Lastly, as members of the comm, as discussed in #5, you can quickly jump around and help each other; I'd suggest that, following this change in auth, you do a couple things in your repo: 
1. Add a codeowners file
2. via the settings lock the master branch from direct commits (optional)
3. set the PRs to require a review by one of the code owners, like so (in settings -> branches):
<img width="744" alt="Screenshot 2019-06-25 at 13 35 17" src="https://user-images.githubusercontent.com/16104054/60268152-aaad6800-98e3-11e9-929f-5be1cf4cade8.png">

(to do this, btw, you need to be admin role in the repo you maintain - if you are not, please let me know and we'll fix that too!)

For anything, feel free to open an issue here or write in the Discord - see you around 👋

**Comment by kelset** [comment]
If I did things right, If I write this now I'll ping you all in one shift move @react-native-community/maintainers 😅

**Comment by FonDorn** [comment]
@kelset will do. Please give me admin role to [Masked View](https://github.com/react-native-community/react-native-masked-view) repo

**Comment by mmazzarolo** [comment]
@kelset thanks for the recap! `react-native-modal` is now up to date. cc: @rewieer

**Comment by CHaNGeTe** [comment]
> there is an eslint config all repos should use, you can read more here [#2](https://github.com/react-native-community/.github/issues/2)

Where is the mentioned eslint?

**Comment by matt-oakes** [comment]
@CHaNGeTe Inside the main React Native repo here: https://github.com/facebook/react-native/tree/master/packages/eslint-config-react-native-community

**Comment by kelset** [comment]
Hey folks, I'm going to close this issue. I should have probably closed it off once I stopped being an owner of the org and while some conversation around this happened I feel that given the "0 executive power" of these conversations it's better to just close them off - so not to give the misleading signal that something is currently being done on my side (or by anyone tbh) around it.

If and when this topic will get picked up again it's much healthier for whoever will actually handle it to just open a new issue. I'm not against the new issue picking up this same conversation, even copy/pasting stuff from here - but I want to close the ones opened up by me off.
