### ISSUE TITLE
Could not resolve project :react-native-camera.

### ISSUE THREAD

**Issue by saraMarzouk** [react-native-community/.github#44]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-camera.
     Required by:
         project :app
      > Cannot choose between the following configurations of project :react-native-camera:
          - generalDebugApiElements
          - mlkitDebugApiElements
        All of them match the consumer attributes:
          - Configuration 'generalDebugApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'generalDebug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
              - Found react-native-camera 'general' but wasn't required.
          - Configuration 'mlkitDebugApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'mlkitDebug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
              - Found react-native-camera 'mlkit' but wasn't required.

**Comment by saraMarzouk** [comment]
this issue appears when trying to run react-native run-android 
more to figure out why this happens :
i want to upgrade react-native-camera using 

> `npm install react-native-camera@latest --save `

**Comment by kelset** [comment]
👋 you should open this issue in the dedicated repo -> https://github.com/react-native-community/react-native-camera
