### ISSUE TITLE
Lean Core repositories

### ISSUE THREAD

**Issue by kelset** [react-native-community/.github#45]
👋 everyone.

I was checking the repositories to understand how many are from the Lean Core and, unless I've made mistakes, there are 25 repositories out of the 70 in the org that have been generated via this effort:

* [x] art
* [x] async-storage
* [x] cli
* [ ] jsc-android-buildscripts
* [ ] react-native-button
* [ ] react-native-cameraroll
* [x] react-native-checkbox
* [x] react-native-clipboard
* [x] react-native-datetimepicker
* [ ] react-native-geolocation
* [ ] react-native-image-editor
* [x] react-native-image-picker-ios
* [x] react-native-masked-view
* [x] react-native-netinfo
* [ ] react-native-picker
* [x] react-native-progress-bar-android
* [x] react-native-progress-view
* [x] react-native-push-notification-ios
* [x] react-native-segmented-control
* [ ] react-native-simple-share
* [ ] react-native-slider
* [ ] react-native-statusbar
* [ ] react-native-tvos
* [x] react-native-viewpager
* [x] react-native-webview

An issue I've noticed about them is that the way the repos "say" they are part of the Lean Core / come from the Lean Core is different, and a bit inconsistent. I mean, some don't even say it -  here are a few examples:

* https://github.com/react-native-community/react-native-masked-view
* https://github.com/react-native-community/react-native-slider#migrating-from-the-core-react-native-module
* https://github.com/react-native-community/cli

I'd propose that we create a simple tag like https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square and we use that across all the different repos 🤗

**Comment by matt-oakes** [comment]
I'm actually not sure that it matters which repos are from the lean core effort and which aren't.

Before they were extracted it was a little arbitrary what was in core and what was a library. Lean Core to me was just moving things out of the core that shouldn't have been there in the first place.

The one thing that might need to be on the READMEs of extracted modules though is some instructions on how to migrate to the new library. There's some basic instructions in the NetInfo module.

**Comment by kelset** [comment]
Yeah, I mean - that's the extent of why I think we should do it:

> The one thing that might need to be on the READMEs of extracted modules though is some instructions on how to migrate to the new library.

And aside from that, I think it would be good to link back to the main Lean Core issue because while we are a subgroup of super active users, many may not be aware of the whys and hows this has happened.

Hence why I proposed a tag - it would be a non-really-invasive way to have a link. A year from now likely we'll reach the point that you are describing of not needing to know / it not being relevant, but at the moment I feel that we are in a transition phase and some people may not know really what is going on.

**Comment by matt-oakes** [comment]
> And aside from that, I think it would be good to link back to the main Lean Core issue because while we are a subgroup of super active users, many may not be aware of the whys and hows this has happened.
>
> Hence why I proposed a tag - it would be a non-really-invasive way to have a link. A year from now likely we'll reach the point that you are describing of not needing to know / it not being relevant, but at the moment I feel that we are in a transition phase and some people may not know really what is going on.

Got it. That makes perfect sense to me then 👍

**Comment by kelset** [comment]
(and, also, I mean - consistency XD if we choose a style let's use it in all the repos - it's driving me crazy 😂)

**Comment by matt-oakes** [comment]
How does this work for you?

[![Lean Core Extracted](https://img.shields.io/badge/Lean%20Core-Extracted-brightgreen.svg)](https://github.com/facebook/react-native/issues/23313)

```
[![Lean Core Extracted](https://img.shields.io/badge/Lean%20Core-Extracted-brightgreen.svg)](https://github.com/facebook/react-native/issues/23313)
```

**Comment by kelset** [comment]
that looks so good ❤️ how did you do it? Is there a tool to create them? :3

**Comment by matt-oakes** [comment]
@kelset shields.io has a load of remade ones which call APIs to get information like download counts, issue counts, and loads of other stuff. Further down that page you can also just put in a title, message, and colour and it will generate you one. It's all hosted by them and based on the URL. They're really useful!

**Comment by matt-oakes** [comment]
Added that badge to the [NetInfo README](https://github.com/react-native-community/react-native-netinfo/tree/15f3d600f6c764e08208d2359559b7c5df5de60b#react-native-communitynetinfo) 👍

**Comment by kelset** [comment]
oh, right. This 😂

Well it's actually a good first issue in a way, no? XD

We could make a tweet via RNComm about it

**Comment by kelset** [comment]
Hey folks, I'm going to close this issue. I should have probably closed it off once I stopped being an owner of the org and while some conversation around this happened I feel that given the "0 executive power" of these conversations it's better to just close them off - so not to give the misleading signal that something is currently being done on my side (or by anyone tbh) around it.

If and when this topic will get picked up again it's much healthier for whoever will actually handle it to just open a new issue. I'm not against the new issue picking up this same conversation, even copy/pasting stuff from here - but I want to close the ones opened up by me off.
