### ISSUE TITLE
about metro bundle when start it close immediatly

### ISSUE THREAD

**Issue by mhmdalii** [react-native-community/.github#47]
In the event of a new project with four days' time, all the solutions were tested with no useful solution. If the problem was solved by the problem, the problem is that the Metro server bundle is a reaction-native run. -android opens up a second and disappears. I am a genius for four days. I have never had a sincere solution, and for knowledge I tried to change the port for live instead of 8081 for any number that is the same.

- Edit: any project old is play , when i create any new project didn't work .
![vCZZs](https://user-images.githubusercontent.com/33903920/60761948-4497b200-a054-11e9-8aa5-a09e29569de1.png)

**Comment by satya164** [comment]
This repo is not for reporting bugs for React Native. Please report bugs in the React Native repo.
