### ISSUE TITLE
Good reasons why your company should get involved

### ISSUE THREAD

**Issue by kelset** [react-native-community/.github#52]
This is a spin off conversation around point 4 from #41 - after I gave my talk at ChainReact last week (video will be updated as some point), I got some cool feedback and a few people asked for resources / a playbook on how to help them explain to their managers / colleagues why having their company involved in Open Source, and in particular in the React Native Community org, would benefit them.

I've read my fair share of articles on the subject, but in here I'd like to try and follow an approach similar to the one used here https://github.com/react-native-community/discussions-and-proposals/issues/134.

Meaning, each comment in this conversation should follow this basic template (feel free to copy paste!):

```
## The real good reason

And here is some more details about that precise reason
```

**Comment by kelset** [comment]
## Code Quality

By having your company adopting / taking care of one of the repositories, you can insure higher quality and better long term support for code that you use in your production app already.

**Comment by kelset** [comment]
## Extra points when hiring

When hiring React Native developers, being able to say that your company actively maintains a library in the React Native Community organisation will give you extra "karma points" / make some developers like you more / give you an edge.

**Comment by kelset** [comment]
## Visibility

Given how widely used the repositories in the org are, your company would surely benefit from the positive resonance of being perceived as a good open source citizen. And this of course also means that more people will be aware of you.

**Comment by pvinis** [comment]
## Developers get paid to do open source

Well, this is more of a "good reason why you should convince your company to get involved", but this will allow devs to actually do some open source they enjoy, while getting paid, as in, do it in company time. Many devs do open source on their free time, and that's awesome for the community, not so awesome for themselves and their work/life balance. Having the freedom to work on that stuff in your day job is great, and it allows for a nice relaxing evening with some friends!

**Comment by xstable** [comment]
How can I be added? Is there a reequest-form or Issue where I can assign?

**Comment by pvinis** [comment]
This issue has suggestions, points and ideas that would help/convince/introduce companies to pay/support devs (employees or otherwise) to do open source. You can add yours here if you have some.

**Comment by kelset** [comment]
@pvinis I think @xstable means how they can get involved in the RNCommunity. There is a dedicated issue for that -> https://github.com/react-native-community/.github/issues/46

But atm as far as I know there is not a precise path. What I would recommend is that you start helping an existing library in the org, reaching out to the maintainer of it and asking what they need help with.

**Comment by kelset** [comment]
Hey folks, I'm going to close this issue. I should have probably closed it off once I stopped being an owner of the org and while some conversation around this happened I feel that given the "0 executive power" of these conversations it's better to just close them off - so not to give the misleading signal that something is currently being done on my side (or by anyone tbh) around it.

If and when this topic will get picked up again it's much healthier for whoever will actually handle it to just open a new issue. I'm not against the new issue picking up this same conversation, even copy/pasting stuff from here - but I want to close the ones opened up by me off.
