### ISSUE TITLE
Take over : react-native-orientation

### ISSUE THREAD

**Issue by xstable** [react-native-community/.github#61]
Don't know where to notice, that the maintainer wan't that "we" (react-native-community) take over his repository.

https://github.com/yamill/react-native-orientation/issues/376

Mabye add an "How to" in our Readme.md how to:

1. Suggest to take over other Projects to r-n-c 
2. Become a Member/Maintainer in r-n-c

(BTW: Please add me to the Community, so that I can support it.)

**Comment by pvinis** [comment]
Do you use this? Would you be willing to maintain this?

**Comment by kelset** [comment]
Hey there - this is the wrong repository to post this.

The correct one is the discussion&proposal repo, similar to what happened here -> https://github.com/react-native-community/discussions-and-proposals/issues/173 

All of that said, there is an ongoing conversation about which packages belong in the org -> https://github.com/react-native-community/discussions-and-proposals/issues/176

Which has not got to a final decision, so probably the first step you should take about this could be for you to get the current maintainer to pass over to you the ownership of the repo (in case you want to be the maintainer).

**Comment by xstable** [comment]
@kelset Maybe would be good to have an short Link in this Page: https://github.com/react-native-community ... to some kind of Overview, so that everybody easily can see where to post such (or other) request. 
ATM it's a bit unclear where to post this kinds of requests, caused of the huge amount of projects.

**Comment by kelset** [comment]
Thanks for the feedback!

Do you have any links/tutorials on how to create that overview for the org page? I'm not sure it's possible 😓

Also, sadly not many things have been "decided" when it comes to these conversation (most of them are still ongoing) which is why it's a bit hard to tell everyone where to go 😓

**Comment by xstable** [comment]
No, don't have an tutorial how to create an overview page. Don't know if it's possible. But you easily can add it as note here as Text... with a link: 
![image](https://user-images.githubusercontent.com/1778068/74353558-60b5bb80-4dba-11ea-8180-976a49e97cb3.png)

**Comment by lucasbento** [comment]
~~Perhaps we can add a `about` repo pinned at the top with some information about the organisation?~~

Edit: nevermind, `.github` already does that 😓
