### ISSUE TITLE
Migrate react-native-config to community

### ISSUE THREAD

**Issue by luancurti** [react-native-community/.github#67]
# Question

How we can migrate the [react-native-config](https://github.com/luggit/react-native-config) to the community? Who can help me? I have permission on the npm package and write in the repository

**Comment by kelset** [comment]
Hello there - as I've said [a few times already](https://github.com/luggit/react-native-config/issues/382#issuecomment-579228124) until [this conversation](https://github.com/react-native-community/discussions-and-proposals/issues/176) has reached an agreement - that repo won't be moved in. Sorry but there's nothing else that can be done around it.
