### ISSUE TITLE
[Proposal] Add Github Discussions to React Native repo

### ISSUE THREAD

**Issue by ecreeth** [react-native-community/.github#68]
## Why it is needed

I think this will help us provide solutions to the most common problems that the React Native repository presents in terms of issues. Also, it will allow users to find the solutions to their problems easier and will reduce the number of duplicate issues.

### sample
![imagen](https://user-images.githubusercontent.com/20761166/80283862-e7efab80-86e8-11ea-9fa5-810e4f45da9b.png)

![imagen](https://user-images.githubusercontent.com/20761166/80311131-d15e5880-87ab-11ea-9d8a-24f0f307539d.png)

**Comment by kelset** [comment]
👋
sadly it's not something that can be just "turned on", looks like those two repo got the feature by directly talking with some GH folks 😓 When it will be available I guess the FB team will consider enabling it.
