### ISSUE TITLE
how to move react-native-qrcode-scanner to be a @react-native-community package instead

### ISSUE THREAD

**Issue by renatobenks** [react-native-community/.github#73]
# Question

Well, a few time ago, I've joined as a maintainer to `react-native-qrcode-scanner` package, to maintain it over @moaazsidat, which it's creator and owner of such package, but has not been possible anymore to keep maintaining this library that has a lot of people using over `react-native-camera`, that usually just needs of a QR code scanner built-in. And discussing with him about how we should go ahead with such a project, and move forward with it, we came up to a conclusion that it would be better to have entire support from @react-native-community instead of keeping supporting just by us as we have been because we don't have a maintainers team behind the scenes, especially because this package it's not a project apart, but actually, a wrapper to `react-native-camera`, with a few adaptions to just QR codes scanning use-cases. Therefore, in general, both are almost the same thing, even because currently, this package doesn't interact directly to native-side, but just uses features around `react-native-camera` that allows by default along with barcodes, QR codes been scanned as well.

So, you might be thinking, why then is this project so important to the point of being moved to @react-native-community? Alright, one of the main reasons is that a lot of people of `react-native-camera` has been using that package to the only purpose of scan bar and QR codes, and a pretty simple fact around it, is that this project can be a huge use-case to finally get started to re-write the entire core of `react-native-camera` to support the scale all the features that have been built in the last few years, thanks of course, to the profound contributions made by a lot of people around the world, but unfortunately, have been turned the core of react-native-camera less extensible, and hard to compose.

So, the idea here would be to have `react-native-qrcode-scanner` on @react-native-community not to just keep maintaining it, but also, to re-write their API, and approach as well, to compose such functionality of scanning codes be integrated on a new `react-native-camera` API core.

I hope had to be pretty clear about what's our idea, which it's by the way, a thing that I've been discussed a lot in the last few months with the people related to such projects, as such @sibelius @moaazsidat @mauriciord

**Comment by mauriciord** [comment]
Evan Bacon @EvanBacon redesigned the Android client QR Scanner as he posted on Instagram Stories.

I think the new Expo Unimodules would help this ideia to evolves a lot

**Comment by kelset** [comment]
👋 there - there is currently an ongoing discussion related to this topic here: https://github.com/react-native-community/discussions-and-proposals/issues/176

and basically, until there is an actual decision around it, no libraries will be added 😓

Since the direction you are suggesting is quite connected to the future of react-native-camera maybe it's simpler to just keep your repo separated, focus on the rewrite of `react-native-camera` and then just merge this feature set in the main `react-native-camera` after the rewrite.
