### ISSUE TITLE
Version release for  react-native-text-input-mask

### ISSUE THREAD

**Issue by johnny-vikrant** [react-native-community/.github#77]
Hi,

Not sure if this is the right place to ask this question.

But [react-native-text-input-mask](https://github.com/react-native-community/react-native-text-input-mask) package seriously need to release a new version with componentWillReceiveProps fix [#141](https://github.com/react-native-community/react-native-text-input-mask/pull/141) which is already merged in the repo but a version has not been release yet.

Is there anyone who have the rights to release the version or ask the maintainer to do so?

**Comment by kelset** [comment]
hey there - I would recommend opening an issue on the repo itself and @-ing the maintainer. Based on [this list](https://github.com/react-native-community/.github/blob/master/MAINTAINERS.md) it's @ivanzotov
